spring:
  datasource:
    url: jdbc:mysql://aa14weyep17kgad.cpstvwcip2y8.eu-north-1.rds.amazonaws.com:3306/assignment?useSSL=false&serverTimezone=UTC
    username: avgona
    password: 123123qwe
server:
  port: 5000